In [2]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('resources/processed/clustered_risk.csv')
df

,longitude,latitude,depth,magnitudeType,magnitude,date,cluster,risk_score
0,43.15720,42.40290,2.33,Md,3.2,2010-01-06,0,0.000158
1,43.00640,42.42030,10.81,Md,3.0,2010-01-15,0,0.003626
2,40.68580,42.85800,17.24,Md,3.0,2010-01-15,0,0.000629
3,42.80920,42.70610,10.87,Md,3.0,2010-01-15,0,0.000186
4,42.99830,42.64920,20.99,Md,3.0,2010-01-19,0,0.000126
...,...,...,...,...,...,...,...,...
30306,33.67944,37.45472,12.67,ML,3.3,2025-01-04,13,0.000005
30307,31.43361,35.74167,14.94,ML,3.0,2025-01-19,13,0.000221
30308,34.08000,36.68500,15.37,ML,3.2,2025-01-24,13,0.000226
30309,31.12750,35.68222,7.00,MW,3.6,2025-01-25,13,0.000000
30310,33.68389,37.52278,7.00,ML,3.0,2025-01-26,13,0.000000

In [5]:
# sort by the date column
df.sort_values(by='date', inplace=True)
df

,longitude,latitude,depth,magnitudeType,magnitude,date,cluster,risk_score
841,36.26650,37.23600,6.92,Ml,3.3,2009-12-31,1,0.000132
25146,40.82130,39.35750,7.02,Md,3.0,2010-01-01,11,0.000064
4410,28.29070,40.11130,7.05,Md,3.0,2010-01-01,2,0.000055
842,36.04030,37.04600,6.61,Md,3.0,2010-01-01,1,0.000170
23582,34.68230,40.32300,6.89,Md,3.0,2010-01-01,9,0.000980
...,...,...,...,...,...,...,...,...
15678,37.88556,38.11778,15.28,ML,3.5,2025-01-29,4,0.000000
25145,45.35611,34.65583,24.90,ML,3.7,2025-01-29,10,0.000000
17654,23.55750,36.27250,7.01,ML,3.3,2025-01-30,5,0.000000
20123,27.10528,36.66722,36.47,ML,3.3,2025-01-30,6,0.000000
17653,26.19056,36.25111,40.28,ML,3.2,2025-01-30,5,0.001012

In [8]:
import matplotlib.pyplot as plt
import seaborn as sns